version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3-management
    ports:
    - "9001:15672"

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 25 && python3 orchestrator.py"
    ports:
    - "8000:80"
    volumes:
    - .:/code
    #- /var/run/docker.sock:/var/run/docker.sock
    #- /usr/local/docker:/usr/local/docker
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure

  # master:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   command: sh -c "sleep 25 && python3 worker.py 1"
  #   volumes:
  #   - .:/code
  #   links:
  #   - rmq
  #   - zoo
  #   depends_on:
  #   - rmq
  #   - zoo
  #   restart: on-failure

  # slave:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   command: sh -c "sleep 25 && python3 worker.py 0"
  #   volumes:
  #   - .:/code
  #   links:
  #   - rmq
  #   - zoo
  #   depends_on:
  #   - rmq
  #   - zoo
  #   restart: on-failure   

  
